-- Run in Supabase SQL Editor.
-- Creates tables used by notice board and admin CMS content editing.

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) <= 120),
  author text check (author is null or char_length(author) <= 30),
  content text not null check (char_length(content) <= 2000),
  attachment_url text,
  attachment_name text check (attachment_name is null or char_length(attachment_name) <= 200),
  created_at timestamptz not null default now()
);

alter table public.board_posts
  add column if not exists attachment_url text;

alter table public.board_posts
  add column if not exists attachment_name text;

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_site_content_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_site_content_updated_at on public.site_content;

create trigger trg_touch_site_content_updated_at
before update on public.site_content
for each row
execute procedure public.touch_site_content_updated_at();

insert into public.site_content (id, content)
values ('global', '{}'::jsonb)
on conflict (id) do nothing;

-- Public storage bucket for CMS image uploads
insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do nothing;

-- Policies for direct browser upload (admin account signed in via Supabase Auth)
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated can upload site-assets'
  ) then
    create policy "Authenticated can upload site-assets"
      on storage.objects
      for insert
      to authenticated
      with check (bucket_id = 'site-assets');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated can update site-assets'
  ) then
    create policy "Authenticated can update site-assets"
      on storage.objects
      for update
      to authenticated
      using (bucket_id = 'site-assets')
      with check (bucket_id = 'site-assets');
  end if;
end $$;
