-- Run in Supabase SQL Editor.
-- Creates tables used by notice board and admin CMS content editing.

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) <= 120),
  author text check (author is null or char_length(author) <= 30),
  content text not null check (char_length(content) <= 2000),
  created_at timestamptz not null default now()
);

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_site_content_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_site_content_updated_at on public.site_content;

create trigger trg_touch_site_content_updated_at
before update on public.site_content
for each row
execute procedure public.touch_site_content_updated_at();

insert into public.site_content (id, content)
values ('global', '{}'::jsonb)
on conflict (id) do nothing;
